export enum ActionTypes {
  INITIALISING = 'INITIALISING',
  BEGIN_PROCESSING_INPUTS = 'BEGIN_PROCESSING_INPUTS',
  CSV_PROCESSING_START = 'CSV_PROCESSING_START',
  CSV_PROCESSING_SUCCESS = 'CSV_PROCESSING_SUCCESS',
  CSV_PROCESSING_ERROR = 'CSV_PROCESSING_ERROR',
  POCKETSMITH_FETCH_START = 'POCKETSMITH_FETCH_START',
  POCKETSMITH_FETCH_SUCCESS = 'POCKETSMITH_FETCH_SUCCESS',
  POCKETSMITH_FETCH_ERROR = 'POCKETSMITH_FETCH_ERROR',
  TRANSACTION_MATCHING_START = 'TRANSACTION_MATCHING_START',
  TRANSACTION_MATCHING_SUCCESS = 'TRANSACTION_MATCHING_SUCCESS',
  TRANSACTION_MATCHING_ERROR = 'TRANSACTION_MATCHING_ERROR',
  INTERACTIVE_MATCHING_START = 'INTERACTIVE_MATCHING_START',
  SET_CURRENT_UNMATCHED_TRANSACTION = 'SET_CURRENT_UNMATCHED_TRANSACTION',
  USER_RESPONSE_FOUND_MATCH = 'USER_RESPONSE_FOUND_MATCH',
  USER_RESPONSE_NO_MATCH = 'USER_RESPONSE_NO_MATCH',
  SET_MANUAL_MATCH_DETAILS = 'SET_MANUAL_MATCH_DETAILS',
  PROCESS_MANUAL_MATCH = 'PROCESS_MANUAL_MATCH',
  INTERACTIVE_MATCHING_COMPLETE = 'INTERACTIVE_MATCHING_COMPLETE',
}

export type Action = {
  type: ActionTypes;
  payload: unknown;
};
