export enum ActionTypes {
  INITIALISING = 'INITIALISING',
  BEGIN_PROCESSING_INPUTS = 'BEGIN_PROCESSING_INPUTS',
  CSV_PROCESSING_START = 'CSV_PROCESSING_START',
  CSV_PROCESSING_SUCCESS = 'CSV_PROCESSING_SUCCESS',
  CSV_PROCESSING_ERROR = 'CSV_PROCESSING_ERROR',
  POCKETSMITH_FETCH_START = 'POCKETSMITH_FETCH_START',
  POCKETSMITH_FETCH_SUCCESS = 'POCKETSMITH_FETCH_SUCCESS',
  POCKETSMITH_FETCH_ERROR = 'POCKETSMITH_FETCH_ERROR',
  TRANSACTION_MATCHING_START = 'TRANSACTION_MATCHING_START',
  TRANSACTION_MATCHING_SUCCESS = 'TRANSACTION_MATCHING_SUCCESS',
  TRANSACTION_MATCHING_ERROR = 'TRANSACTION_MATCHING_ERROR',
}

export type Action = {
  type: ActionTypes;
  payload: unknown;
};
